#########################
#                       #
# viper WebApp 配置文件 #
#                       #
#########################


########## 环境配置
env = "dev"

########## server 相关配置
[server]
# server 运行地址
addr = ":4869"
# gin mode ，可选值： debug 、 test 、 release
mode = "debug"
# 开启 pprof
pprof = true
# 服务器从 accept 到读取 body 的超时时间（秒）
read_timeout = 5
# 服务器从 accept 到写 response 的超时时间（秒）
write_timeout = 5

########## apidocs 相关配置
[apidocs]
# 文档标题
title = "pink-lady swagger apidocs"
# 文档描述
desc = "Using pink-lady to develop gin app on fly."
# 请求地址，端口要和 server.addr 一致，浏览器访问时需要区分 127.0.0.1 和 localhost
host = "localhost:4869"
# 请求地址的 basepath
basepath = "/"
# 支持的请求 schemes
schemes = ["http"]

########## basic auth 相关配置
[basic_auth]
# 登录用户名
username = "admin"
# 登录密码
password = "admin"

########## MySQL 相关配置
# mysql 按不同环境可以添加多个配置
# 本地配置
[mysql.localhost]
host = "localhost"
port = 3306
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10
conn_timeout = 3
read_timeout = 5
write_timeout = 5
# 其他环境
[mysql.other]

########## SQLite3 相关配置
[sqlite3.dev]
dbname = "sqlite3.dev.db"
log_mode = false

########## Postgres 相关配置
[postgres.localhost]
host = "localhost"
port = 5432
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10
disable_ssl = true

########## MsSQL 相关配置
[mssql.localhost]
host = "localhost"
port = 1433
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10

########## Redis 相关配置
# redis 按不同环境可以添加多个配置
[redis]
    # 本地配置
    [redis.localhost]
        mode = "normal"
        address = "localhost:6379"
        password = ""
        dbindex = 0
        master = ""
    [redis.other]
